### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by jsbean** [jsbean/HansTools#12]

**Comment by hanstutschku** [comment]
Hi James,

This is the link to the SQL wrapper I’m using

https://github.com/FahimF/SQLiteDB <https://github.com/FahimF/SQLiteDB>



The last commit puts the reading into an Event class


I guess I have to leave now.

Talks to you later,

Best, Hans

**Comment by jsbean** [comment]
Closing this for now. If we break out at least some parts of this, we can add logical tests where it makes sense.
