### ISSUE TITLE
Make Fader.fade(...) logarithmic

### ISSUE THREAD

**Issue by jsbean** [jsbean/HansTools#20]
`Fader` currently fades linearly, and it sounds like it. Make logarithmic scaler.

**Comment by hanstutschku** [comment]
In all my works I’m rarely fading sounds. I do all of it with lowpass filters going to 0 Hz, which
makes it much more natural.
Now that we have this AudioKit, this should be possible ??!!

**Comment by jsbean** [comment]
Hmmm, yes -- good idea! We'll look into that.
