### ISSUE TITLE
Implement fade with EQ

### ISSUE THREAD

**Issue by jsbean** [jsbean/HansTools#21]
Instead of fading with `AKAudioPlayer.volume`, use lo-pass filter sweep down to 0hz.

Look into:
- [AKHighShelfFilter](http://audiokit.io/docs/Classes/AKHighShelfFilter.html)
- [AKLowPassButterworthFilter](http://audiokit.io/docs/Classes/AKLowPassButterworthFilter.html) 
- [AKThreePoleLowPassFilter](http://audiokit.io/docs/Classes/AKThreePoleLowpassFilter.html)

**Comment by hanstutschku** [comment]
The fade out logic has a small problem:

if the next sound file is started after the previous ended, the new sound file will grab
the same player, as it is free now.
Therefore the newly started sound file will be fade out immediately as the dico points to that player for
the previous file.
I need to rethink the logic.

In my old implementation I was not looking into the .first free player but always grabbing circularly the next
one within the pool.

**Comment by hanstutschku** [comment]
I integrated the AirTurn class, but don’t get it to work with just the bridging header.
I need to refactor the code into swift. The ‘makeFirstResponder” for the textfield has apparently
changed under swift.

**Comment by jsbean** [comment]
Is the fade out logic fixed, or do we still need to deal with that?

**Comment by hanstutschku** [comment]
I tried but failed

Hans

**Comment by hanstutschku** [comment]
I’m at BU this morning and I’m heading to concerts and a conference in the UK tomorrow.
Not sure how much I’m getting done before leaving.

If you look in to activateEvent in ViewController you will see my attempt to decide whether or not
to fade.
But .isPlaying or .isStopped is not very accurate.
Sometimes it is ‘off’ by a couple of hundred milliseconds, meaning that the state is not updated
at the very moment of stopping the player.

best, Hans

**Comment by jsbean** [comment]
Ok, I will poke at it.

**Comment by jsbean** [comment]
With [this commit](https://github.com/audiokit/AudioKit/commit/73a6abf2a7a58af86a90e96667828804146426e6) @ AudioKit, it looks like we can make this `.isPlaying` / `.isStopped` functionality more accurate. I will look into hooking this in tomorrow.

**Comment by hanstutschku** [comment]
Hi James
I will look into it after Hydra.
Best, Hans

**Comment by jsbean** [comment]
Closing this for now. We can reopen it once we have comfortable footing.
