### ISSUE TITLE
Implement MIDI

### ISSUE THREAD

**Issue by jsbean** [jsbean/HansTools#22]
[Here](https://github.com/audiokit/AudioKit/commit/7d00ba80c31b916e096d8097f7e7ca5026f719e9) is a commit to AudioKit that may have addressed some of your MIDI issues. Not sure, but worth looking into.

**Comment by jsbean** [comment]
At some point, I'll update my forked version of AudioKit to address this.

**Comment by hanstutschku** [comment]
Hi James,

greetings from Birmingham.
How can I test this commit of AudioKit? 
It does not seem to be integrated into the main AudioKit download on github.
Can one download just this commit?

I hope to find some time over the next days to follow videos on delegation
to get a clearer picture.

Thanks, Hans

**Comment by jsbean** [comment]
Oh! This passed by me: I am shifting the AudioKit framework to look at the `develop` branch, which is where the updated MIDI stuff is taking place. Will be pushed shortly.

**Comment by jsbean** [comment]
Do a `git pull origin settings` when you get back to things. See if AKMIDI-related activities are working out yet.

**Comment by hanstutschku** [comment]
Hi James,

wow, I’m seeing hundreds of lines of new code files appearing in the terminal
Though, when opening the Xcode project they don’t seem to be integrated yet.
Guessing from their names (EnumTools, DirectionTools, MetronomeController etc).
you are preparing more higher-level classes to deal with timing.
I can’t really check out the MIDI related questions, as I did not take my BlueTooth Midi
pedal on the trip.

I hope I get some time over the next days to continue with the AitTurn delegate.

Best, Hans

**Comment by jsbean** [comment]
Yes, all of that relates to a nascent `MetronomeController` that is waiting in the wings. I was doing an initial test to see if all of that will integrate nicely when the time is right. Apologies for the extra gunk.

The `MetronomeController`, which will likely be generalized further, will provide a clean interface to control timed things (flashing metronome, progress bar, etc.). This will prevent you from having to instantiate all of these `NSTimers` and throwing around global variables.

Keep hitting at the AirTurn delegate!

**Comment by jsbean** [comment]
Closing this for now. We can reopen this when it becomes necessary.
