### ISSUE TITLE
Revert back to original global variable timer / progress bar

### ISSUE THREAD

**Issue by jsbean** [jsbean/HansTools#32]
My experiments with the progress bar are mediocre. For now, I think I will revert back to the Hans-implemented versions.

I will work more atomically on each object and the timing mechanisms independently, and if they are sufficient at some point, I will reintegrate.

**Comment by hanstutschku** [comment]
Hi James,

Hope you enjoy the summer.
Please keep me posted about your discoveries.
If you have a version I should clone/merge/pull, let me know.

I’m enjoying a couple of days in 33 to test more ambisonics technics, before
heading to Sao Paulo.

Best, Hans
