### ISSUE TITLE
Implement countoff

### ISSUE THREAD

**Issue by jsbean** [jsbean/HansTools#44]

**Comment by jsbean** [comment]
Closing this for now, because Tony has hands free. We can reopen this when necessary.

**Comment by hanstutschku** [comment]
Hi James,
I see you are going through a long list of issues and work hard. Thanks for all of it. 
Just a quick comment on this one: if she could trigger with the pedal that would be preferred, as she uses often her hands to modulate the sounds of the mouth. 

Hans

**Comment by jsbean** [comment]
Ahh, totally. Will look into that now!

**Comment by jsbean** [comment]
Reclosing this, as it actually doesn't have to do with hands or `AirTurn`.

See #112, instead.
