### ISSUE TITLE
Delay in audio file playback

### ISSUE THREAD

**Issue by jsbean** [jsbean/HansTools#98]
There is currently a slight delay between hitting the `touchBar` and the start of audio.

I am getting measurements of ~`0.005`–`0.007` seconds (5-7 ms), but I can't pin down anything more than that. There must be something deeper down in the `AVAudioPlayerNode`, which is the underlying implementation.

I have tried digging into the `AudioKit` implementation details, moving around the buffer scheduling and preparation, but still not getting better.

**Comment by jsbean** [comment]
@hanstutschku, let me know if this has been improved on your devices now that we have remove the pitch shifting.

**Comment by hanstutschku** [comment]
James,

the delay is considerably smaller without the pitch shift, but still bigger than with OpenAL.

Here are some errors while loading the soundfiles (copied from Xcode). No idea whether those are helpful for you.

2016-11-25 18:54:05.921 SwiftAudioKitTest[2458:2051657] _BSMachError: (os/kern) invalid capability (20)
2016-11-25 18:54:05.922 SwiftAudioKitTest[2458:2051657] _BSMachError: (os/kern) invalid name (15)
AKAudioPlayer -> File with "voice-unrooted-001.caf” Reloaded


Another detail I’m seeing now:
when you let an event totally run out and start the next one after complete silence, they play sometimes,
sometimes not (meaning getting a fade out).
15 play, then wait till silence
16 play, then wait till silence
17 will not play

(sorry I’m not good at github and don’t remember how to enter those issues properly)

**Comment by jsbean** [comment]
Unless @hanstutschku, you feel different, I'd say this can be closed.

If we find any instances of lag in the newly implemented audio playback scheme, we can reopen this issue.
